default:
	@just --list

setup_release: clean
    mkdir -p build
    cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../riscv.cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
    @echo Done. Now run Ninja in build.

setup_debug: clean
    mkdir -p build
    cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../riscv.cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
    @echo Done. Now run Ninja in build.

clean:
    rm -rf build

